language: node_js
node_js:
- "node"

cache:
  pip: true
  directories:
  - node_modules # NPM packages

install:
- pip install grow --user
- npm install -g gulp-cli
- npm install

jobs:
  include:
    - stage: build
      script:
        - grow build --re-route --locale None --locale en --locale de --locale es
        - pip install gsutil --user # can't do this before grow has run, as the oath2client is incompatible
        - gsutil -m cp -r build/* gs://ampproject-b5f4c.appspot.com
    - stage: build
      script:
      - grow build --re-route --locale fr --locale id --locale it --locale ja --locale ko --locale pt_BR
      - pip install gsutil --user # can't do this before grow has run, as the oath2client is incompatible
      - gsutil -m cp -r build/* gs://ampproject-b5f4c.appspot.com
    - stage: build
      script:
      - grow build --re-route  --locale ko --locale pt_BR --locale ru --locale tr --locale zh_CN
      - pip install gsutil --user # can't do this before grow has run, as the oath2client is incompatible
      - gsutil -m cp -r build/* gs://ampproject-b5f4c.appspot.com
    - stage: deploy
      install:
        - npm install -g firebase-tools
      script:
        - 'if [ "${TRAVIS_BRANCH}" = "production" ]; then firebase use production; fi'
        - 'if [ "${TRAVIS_BRANCH}" = "master" ]; then firebase use staging; fi'
        - mkdir build
        - gsutil -m cp -r gs://ampproject-b5f4c.appspot.com/* build
        - ls build
#        - firebase deploy --token "$FIREBASE_TOKEN" --non-interactive

branches:
  only:
  - production
  - master
  - parallel

env:
  global:
    secure: RRx3CaLmCC0rA+MOYXTI3HTAMc2TI9AQcodUfZhr+vNEL8d0q09EZkYU/TjkRx9VQ1paOT1AmxNQJtHhysIS7B/pSAZoNG9bPC5UXmiZHVLbRB4qPmMMte9zdfKanGY3/g3zt2qOTUVVL4ymDy5xK2uYZ/KgkrDx1gGH3mSoTO6gK79I4nisJYDcRfzI/UUvrNkdjlFYrFnZbnMdnqZSryuv7CrdZWpYtLDryzJ+bcgq6Vr2liiKwmVb+/tff3EblAzBcWMAM4I0MzRaM+Mahw0EEENc24brtVoQTbvSdXXJ9CEIfWjykSyZh0WrZkx3tKY95GDr9PCHEkyI5d2kUGYDbRjjrEuBEdPTcjx6zZ2vXUlVPeDxNwLO1WZwVy0Om1dg/jwPjVDtsubjBaC+4XezJCywaZruGD6Q0iStemMVapN19SbGJzo9uYG8EvVB4OFlmY2l/fOadTIC9YHpYJREhGc2DBW9jHfTK1dgyW1JpnFgieEOSw24gsvbxSSV5db7tJU36Pt1Kkcu3IZnYyHlBUmYKZ24cizh6azfkHRaLvSvdJuvx0euuoz/WOJ77toUD6wPc0/OtrKnkCfQowtciMdnKNhuu4JpegdZ9gQqpV2gQ0XpPgxc4afKCd0L5QiUNFCu1J+fQ0obclqWZpC0VzHdDpNMckv4I7XqnhI=