language: node_js
node_js:
- 8

cache:
  pip: true
  directories:
  - node_modules # NPM packages

install:
- pip install grow --user
- npm install -g gulp
- npm install -g firebase-tools
- npm install

jobs:
  include:
    - stage: build-first
      script: grow build --re-route --locale None --locale en --locale de --locale es
    - stage: build-second
      script: grow build --re-route --locale None --locale fr --locale id --locale it --locale ja --locale ko --locale pt_BR --locale ru --locale tr --locale zh_CN
    - stage: deploy
      install:
        - npm install -g firebase-tools
      script:
        - 'if [ "${TRAVIS_BRANCH}" = "production" ]; then firebase use production; fi'
        - 'if [ "${TRAVIS_BRANCH}" = "master" ]; then firebase use staging; fi'
        - mkdir build
        - gsutil -m cp -r gs://ampproject-b5f4c.appspot.com/* build
        - ls build
#        - firebase deploy --token "$FIREBASE_TOKEN" --non-interactive

branches:
  only:
  - production
  - master
  - parallel

env:
  global:
    secure: RRx3CaLmCC0rA+MOYXTI3HTAMc2TI9AQcodUfZhr+vNEL8d0q09EZkYU/TjkRx9VQ1paOT1AmxNQJtHhysIS7B/pSAZoNG9bPC5UXmiZHVLbRB4qPmMMte9zdfKanGY3/g3zt2qOTUVVL4ymDy5xK2uYZ/KgkrDx1gGH3mSoTO6gK79I4nisJYDcRfzI/UUvrNkdjlFYrFnZbnMdnqZSryuv7CrdZWpYtLDryzJ+bcgq6Vr2liiKwmVb+/tff3EblAzBcWMAM4I0MzRaM+Mahw0EEENc24brtVoQTbvSdXXJ9CEIfWjykSyZh0WrZkx3tKY95GDr9PCHEkyI5d2kUGYDbRjjrEuBEdPTcjx6zZ2vXUlVPeDxNwLO1WZwVy0Om1dg/jwPjVDtsubjBaC+4XezJCywaZruGD6Q0iStemMVapN19SbGJzo9uYG8EvVB4OFlmY2l/fOadTIC9YHpYJREhGc2DBW9jHfTK1dgyW1JpnFgieEOSw24gsvbxSSV5db7tJU36Pt1Kkcu3IZnYyHlBUmYKZ24cizh6azfkHRaLvSvdJuvx0euuoz/WOJ77toUD6wPc0/OtrKnkCfQowtciMdnKNhuu4JpegdZ9gQqpV2gQ0XpPgxc4afKCd0L5QiUNFCu1J+fQ0obclqWZpC0VzHdDpNMckv4I7XqnhI=

deploy:
  provider: gcs
  access_key_id: GOOG363HBMUBIVAZ465P
  secret_access_key:
    secure: Ww5fXRilIT2MOTHD+OvWeSMN6GeXrR9hvPo6ERd2vFPK3g6sB2F1wvq3U7QJo1S3JjCQ3zQQLjek9WLqem5ALZgWJJMEcMnJCla0Zt/D9VGlkrgw5X2Kk9X6+ff6XLBD2OATOXvoPOlQLPUKAIR4YRrI8I2GSizT19plkpwIKGz2MxTHHWpsQvI5LQS4mRzSWcOtSKQKfejWSyix7+1LFkpthxijzn9Nx0hD66dnSCTPdEZSrb5HoYOSbm8oeMIv5JflyOWoAs4HYke5muQCyfUxoPal2ioEkrf2bHYQsiXbigqxloDU3y+cK0JDKigBvCL2rkbaVDk08N+X3GoUTCnKuVH9vjVAHJiROf/wfMzCm8pmUgTh0QFyVGdzUaFBbShSAn18xR6h2kM/wMFNQGS0baqq6LMNQX0yt7ACdw2bHFDvD4ZoPuTTKr0Ji0a5WwD0f1XdX185oPftMJb0y1HT6hnmJriOuppIM6oDs7dbiJnqp+OqZyzFp6bSWmwUrn4zGcbjCGKl+ol8s3uRWC2XksoArTCHZDj4Aw5PkYW+N2C3KzYSYykikUvZvLiq9QWTeq0AFwDlH0K+vrUDraXRPBWP4opPednNQRo7SPC6IY5i0tJkNdNQKbfoEsDV8LG36OF9TjmA9S96FN5cleYp6iqJ3UEwOC6cdVarCXw=
  bucket: ampproject-b5f4c.appspot.com
  local-dir: build
  on:
    repo: ampproject/docs
