language: node_js
node_js:
- "node"

git:
  depth: 3

cache:
  pip: true
  directories:
  - node_modules

install:
- pip install grow --user
- npm install -g gulp-cli
- npm install

jobs:
  include:
    - stage: build
      script:
      - travis_wait grow build --re-route --locale None --locale en --locale de --locale es
      - pip install gsutil --user # can't do this before grow has run, as the oath2client is incompatible
      - 'if [ "${TRAVIS_BRANCH}" = "production" ]; then gsutil -m cp -r build/* gs://ampproject-b5f4c.appspot.com; fi'
      - 'if [ "${TRAVIS_BRANCH}" = "parallel" ]; then gsutil -m cp -r build/* gs://ampproject-staging.appspot.com; fi'
    - stage: build
      script:
      - travis_wait grow build --re-route --locale fr --locale id --locale ja
      - pip install gsutil --user # can't do this before grow has run, as the oath2client is incompatible
      - 'if [ "${TRAVIS_BRANCH}" = "production" ]; then gsutil -m cp -r build/* gs://ampproject-b5f4c.appspot.com; fi'
      - 'if [ "${TRAVIS_BRANCH}" = "parallel" ]; then gsutil -m cp -r build/* gs://ampproject-staging.appspot.com; fi'
    - stage: build
      script:
      - travis_wait grow build --re-route  --locale it --locale ko --locale pt_BR
      - pip install gsutil --user # can't do this before grow has run, as the oath2client is incompatible
      - 'if [ "${TRAVIS_BRANCH}" = "production" ]; then gsutil -m cp -r build/* gs://ampproject-b5f4c.appspot.com; fi'
      - 'if [ "${TRAVIS_BRANCH}" = "parallel" ]; then gsutil -m cp -r build/* gs://ampproject-staging.appspot.com; fi'
    - stage: build
      script:
      - travis_wait grow build --re-route  --locale tr --locale zh_CN --locale ru
      - pip install gsutil --user # can't do this before grow has run, as the oath2client is incompatible
      - 'if [ "${TRAVIS_BRANCH}" = "production" ]; then gsutil -m cp -r build/* gs://ampproject-b5f4c.appspot.com; fi'
      - 'if [ "${TRAVIS_BRANCH}" = "parallel" ]; then gsutil -m cp -r build/* gs://ampproject-staging.appspot.com; fi'
    - stage: deploy
      install:
      - npm install -g firebase-tools
      script:
      - 'if [ "${TRAVIS_BRANCH}" = "production" ]; then firebase use production; fi'
      - 'if [ "${TRAVIS_BRANCH}" = "parallel" ]; then firebase use staging; fi'
      - mkdir build
      - pip install gsutil --user
      - 'if [ "${TRAVIS_BRANCH}" = "production" ]; then gsutil -m cp -r gs://ampproject-b5f4c.appspot.com/* build; fi'
      - 'if [ "${TRAVIS_BRANCH}" = "parallel" ]; then gsutil -m cp -r gs://ampproject-staging.appspot.com/* build; fi'
      - gsutil -m cp -r gs://ampproject-b5f4c.appspot.com/* build
      - ls build
# TODO: renenable        - firebase deploy --token "$FIREBASE_TOKEN" --non-interactive

branches:
  only:
  - production
  - master
  - parallel

env:
  global:
    secure: RRx3CaLmCC0rA+MOYXTI3HTAMc2TI9AQcodUfZhr+vNEL8d0q09EZkYU/TjkRx9VQ1paOT1AmxNQJtHhysIS7B/pSAZoNG9bPC5UXmiZHVLbRB4qPmMMte9zdfKanGY3/g3zt2qOTUVVL4ymDy5xK2uYZ/KgkrDx1gGH3mSoTO6gK79I4nisJYDcRfzI/UUvrNkdjlFYrFnZbnMdnqZSryuv7CrdZWpYtLDryzJ+bcgq6Vr2liiKwmVb+/tff3EblAzBcWMAM4I0MzRaM+Mahw0EEENc24brtVoQTbvSdXXJ9CEIfWjykSyZh0WrZkx3tKY95GDr9PCHEkyI5d2kUGYDbRjjrEuBEdPTcjx6zZ2vXUlVPeDxNwLO1WZwVy0Om1dg/jwPjVDtsubjBaC+4XezJCywaZruGD6Q0iStemMVapN19SbGJzo9uYG8EvVB4OFlmY2l/fOadTIC9YHpYJREhGc2DBW9jHfTK1dgyW1JpnFgieEOSw24gsvbxSSV5db7tJU36Pt1Kkcu3IZnYyHlBUmYKZ24cizh6azfkHRaLvSvdJuvx0euuoz/WOJ77toUD6wPc0/OtrKnkCfQowtciMdnKNhuu4JpegdZ9gQqpV2gQ0XpPgxc4afKCd0L5QiUNFCu1J+fQ0obclqWZpC0VzHdDpNMckv4I7XqnhI=